-- AlterTable
ALTER TABLE "Lobster" ADD COLUMN "maxHp" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Lobster" ADD COLUMN "attackDamage" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Lobster" ADD COLUMN "friendshipChance" DOUBLE PRECISION NOT NULL DEFAULT 0.2;
ALTER TABLE "Lobster" ADD COLUMN "attackHitChance" DOUBLE PRECISION NOT NULL DEFAULT 0.8;
ALTER TABLE "Lobster" ADD COLUMN "critChance" DOUBLE PRECISION NOT NULL DEFAULT 0.05;
ALTER TABLE "Lobster" ADD COLUMN "pendingLevelUpLevel" INTEGER;
